name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        install_components: 'beta,alpha'

    - name: Build Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/kube-429706/my-app:${{ github.sha }} .

   

    - name: Push Docker image
      run: |
          # Authenticate with Google Cloud
          echo ${{ secrets.GCP_SA_KEY }} | gcloud auth activate-service-account --key-file=-
          
          # Configure Docker to use the Google Cloud credentials
          gcloud auth configure-docker us-central1-docker.pkg.dev
          
          # Tag the Docker image
          docker tag my-app:${{ github.sha }} us-central1-docker.pkg.dev/kube-429706/my-app:${{ github.sha }}
          
          # Push the Docker image to Artifact Registry
          docker push us-central1-docker.pkg.dev/kube-429706/my-app:${{ github.sha }}
      

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: my-cluster
        location: us-central1-a

    - name: Deploy to GKE
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        kubectl apply -f ingress.yaml # Optional
