name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        install_components: 'beta,alpha'

    - name: Build Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/kube-429706/my-app:${{ github.sha }} .
  
    - name:        Push Docker image
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev

        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-app/my-app${{ github.sha }}

        # docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-app/my-app:${{ github.sha }}

      env:
          CLOUDSDK_METRICS_ENVIRONMENT: github-actions-setup-gcloud
          CLOUDSDK_METRICS_ENVIRONMENT_VERSION: 1.1.1
  
      

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: my-cluster
        location: us-central1-a

    - name: Deploy to GKE
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        kubectl apply -f ingress.yaml # Optional
